---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-pod-eip-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-pod-eip-controller-rolebinding
subjects:
- kind: ServiceAccount
  name: aws-pod-eip-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: aws-pod-eip-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pec-config
  namespace: kube-system
data:
  config.yaml: |
    log:
      level: warn
      format: json
    clusterName: <cluster-name>
    vpcID: 
    region: 
    channelSize: 20
    kubeConfigPath: 
    watchNamespace: <watch-namespace>
    resyncPeriod: 600
    recycleOption:
      enable: false
      period: 3600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: aws-pod-eip-controller
  labels:
    app.kubernetes.io/name: aws-pod-eip-controller
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-pod-eip-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aws-pod-eip-controller
    spec:
      containers:
      - image: <account>.dkr.ecr.<region-code>.amazonaws.com/aws-pod-eip-controller
        imagePullPolicy: Always
        name: aws-pod-eip-controller
        volumeMounts:
        - name: config-volume
          mountPath: /etc/aws-pod-eip-controller
      serviceAccountName: aws-pod-eip-controller
      volumes:
      - name: config-volume
        configMap:
          name: pec-config
          items:
          - key: config.yaml
            path: config.yaml
  